export { UsersTable } from "./UsersTable"
export { SearchMovies } from "./Search"
export { StarRating } from "./Rating"
export { PaginationDiv } from "./Pagination"
export { DetailCard } from "./Detail"
export { UserList } from "./UserList"
export { MoviesList } from "./MoviesList"